[package]
name = "raylib-rs-plain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib-rs-plain-sys = { version = "0.1.0", path = "../raylib-rs-plain-sys" }
