[tasks.build-plain-sys]
workspace = false
command = "cargo"
args = ["build"]
cwd = "raylib-plain-sys"

[tasks.build-plain]
workspace = false
command = "cargo"
args = ["build"]
cwd = "raylib-plain"
dependencies = ["build-plain-sys"]
