name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    # - run: rustup toolchain install stable-gnu
    - run: rustup default stable-gnu
    - run: rustup component add rustfmt
    - run: rustup show
    - run: rustup component list --installed
    - run: cargo --version
      
    # Enable cc.
    - name: Display PATH
      run: echo $Env:PATH
    - run: copy "C:\mingw64\bin\gcc.exe" "C:\mingw64\bin\cc.exe"
    - run: dir "C:\mingw64\bin"
    - run: gcc --version
    - run: cc --version
      
    - run: cargo install cargo-make
    - run: cargo make build-plain -vv
    - run: cargo test _ci -- --nocapture
    - run: rustup component add clippy
    - run: cargo clippy
