name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    # - run: rustup toolchain install stable-gnu
    - run: rustup default stable-gnu
    - run: rustup component add rustfmt
    - run: rustup show
    - run: rustup component list --installed
    - run: cargo --version
    - run: cargo build -vv
    - run: cargo test _ci -- --nocapture
    - run: cargo clippy
