name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup show
    - run: cargo --version
    - name: Build
      run: cargo build -vv
    - name: Run tests
      run: cargo test --verbose
